trigger:
  branches:
    include:
      - master
pr:
  branches:
    include:
      - master

variables:
  pythonVersion: 3.12
  venvDirectory: $(System.DefaultWorkingDirectory)/venv

jobs:
  - job: test
    displayName: test
    pool:
      vmImage: windows-2019
    steps:
      - task: UsePythonVersion@0
        displayName: Use Python $(pythonVersion)
        inputs:
          versionSpec: $(pythonVersion)
      - script: python -m pip install -r requirements/ci.txt
        displayName: python -m pip install -r requirements/ci.txt
      - script: pipenv install --python $(pythonVersion) -r requirements/test.txt
        displayName: pipenv install -r requirements/test.txt
      - script: pipenv install -e .
        displayName: pipenv install -e .
      - script: pipenv run pytest
        displayName: pipenv run pytest
