name: Release version and publish package

on:
  workflow_run:
    workflows: ["Build and test"]
    types: [completed]

concurrency:
  group: release-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  # Retrieve artifacts after build and test run
  check-artifacts:
    name: Check artifacts from build run
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    permissions:
      actions: read  # Required to download artifacts from other workflow runs
    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093
        with:
          name: dists
          path: dist/
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Upload artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: dists
          path: dist/
          if-no-files-found: error
          retention-days: 1

  # Create release
  release:
    if: |
      github.event.workflow_run != 'pull_request' &&
      github.event.workflow_run.head_branch == github.event.repository.default_branch
    name: Create release and publish package
    runs-on: ubuntu-latest
    needs:
      - check-artifacts
    outputs:
      condition: ${{ steps.release.outputs.release-condition }}
    steps:
      - name: Create GitHub release
        id: release
        uses: lorengordon/actions-workflows/.github/actions/release@9a5eaf0ce604c640dab9c7d79e0a9b9643bd69f7
        with:
          release-token: "${{ secrets.GH_RELEASES_TOKEN }}"

      - run: 'echo "Release condition: ${{ steps.release.outputs.release-condition }}"'
      - run: 'echo "condition=${{ steps.release.outputs.release-condition }}" >> "$GITHUB_OUTPUT"'

  # Publish to PyPI
  publish:
    name: Create release and publish package
    runs-on: ubuntu-latest
    needs:
      - release
    if: needs.release.outputs.condition == 'true'
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093
        with:
          name: dists
          path: dist/

      - run: ls -al dist/

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc
